language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3
install:
  - python setup.py install
  - pip install pytest pytest-cov coveralls
script: 
  - py.test --cov flask_init --basetemp=temp tests
after_success:
  - coveralls
after_script:
  - rm -rf temp/
